import type { FaliuMeritBenefit } from "./faliu-merit-benefits";

const QIBAO_TA_SECTION_TITLE = "七寶塔品第十一";

export const T0263_JUAN_6_QIBAO_MERIT_BENEFITS: FaliuMeritBenefit[] = [
  {
    id: "t0263-006-051",
    category: "寶塔讚法",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "善哉！善哉！世尊安住！審如所言，道德玄妙超絶無侣，慧平等一猶如虚空，實無有異。",
    anchorText: "善哉！善哉！世尊安住",
    note: "七宝塔自然发声赞叹佛所说法玄妙无侣、平等如空。",
  },
  {
    id: "t0263-006-052",
    category: "聽受成道",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "吾會當以此正法華經當自修成，使諸菩薩皆得聽受，然後乃坐於佛樹下逮，成無上正真之道。",
    anchorText: "吾會當以此正法華經當自修成",
    note: "多宝如来本愿以《正法华经》自修成就，并令诸菩萨听受而后成道。",
  },
  {
    id: "t0263-006-053",
    category: "開化得道",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "爲諸十方講説經法，開化一切皆令得道。",
    anchorText: "爲諸十方講説經法",
    note: "经文说明多宝如来为十方讲说经法，开化一切令得道。",
  },
  {
    id: "t0263-006-054",
    category: "見塔功德",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "若見塔者悉得其所，功德難限。",
    anchorText: "若見塔者悉得其所",
    note: "多宝如来临灭度时明说见塔者功德难以限量。",
  },
  {
    id: "t0263-006-055",
    category: "法華作證",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "十方世界其有講説此法華經，吾七寶塔涌，現諸佛所説經處，其舍利身在七寶塔，贊言善哉！",
    anchorText: "十方世界其有講説此法華經",
    note: "多宝如来誓愿凡十方有说《法华经》处，七宝塔即涌现作证赞叹。",
  },
  {
    id: "t0263-006-056",
    category: "精進成佛",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "用衆生故不惜身命，精進不懈行權方便，布施、持戒、忍辱、精進、一心、智慧，求頭與頭求眼與眼，求鼻與鼻求耳與耳求，手足肢體妻子侍從，七寶車乘象馬衣裘，國邑墟聚恣人所求，無所愛惜自致得佛。",
    anchorText: "用衆生故不惜身命",
    note: "佛以自身往昔菩萨行说明为众生不惜身命、修六度方便而成佛。",
  },
  {
    id: "t0263-006-057",
    category: "講經蒙恩",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "講正法華開化一切，使蒙其恩。",
    anchorText: "講正法華開化一切",
    note: "多宝如来请释迦讲《正法华》，开化一切众生，使蒙法恩。",
  },
  {
    id: "t0263-006-058",
    category: "聞名離苦",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "設聞多寶佛，知其名號者，未曽畏終始，不復遭苦患多。",
    anchorText: "設聞多寶佛，知其名號者",
    note: "偈颂说闻知多宝佛名号者，不畏生死终始，不复遭诸苦患。",
  },
  {
    id: "t0263-006-059",
    category: "奉法成道",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "一切所供養，奉法爲最上，分别空無慧，自致得佛道。",
    anchorText: "一切所供養，奉法爲最上",
    note: "偈颂再次赞法供养最上，并以分别空无慧而自致佛道。",
  },
  {
    id: "t0263-006-060",
    category: "宣經一乘",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "宣揚法華經，以示諸不及，解本無三乘，順一無上真。",
    anchorText: "宣揚法華經，以示諸不及",
    note: "宣扬《法华经》能显示无三乘、顺入一无上真。",
  },
  {
    id: "t0263-006-061",
    category: "聞經現塔",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "今者多寶如來、至真，在斯塔寺，遥聞説此正法華典，是以涌出，贊言善哉！",
    anchorText: "遥聞説此正法華典",
    note: "多宝如来因遥闻说此《正法华》而涌现赞叹，突显此经殊胜。",
  },
  {
    id: "t0263-006-062",
    category: "開發大道",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "願垂恩慈加以威神，使諸來者各得其所開發大道。",
    anchorText: "願垂恩慈加以威神",
    note: "大辩菩萨请佛加被，使会众得见多宝佛形，各得开发展大道。",
  },
  {
    id: "t0263-006-063",
    category: "見佛供養",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "我之塔寺所至方面，聽此經典，設諸如來及四部衆，欲睹吾身，隨其十方之所欲願，皆當得見，咸共供養於此化像。",
    anchorText: "我之塔寺所至方面，聽此經典",
    note: "多宝如来本誓随说经之处令诸佛与四众得见其身，共作供养。",
  },
  {
    id: "t0263-006-064",
    category: "十方佛集",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "一切世界所化如來，講説法者皆令詣此。",
    anchorText: "一切世界所化如來",
    note: "经文说明十方讲说法的化佛皆来集会，彰显此经为诸佛所共证。",
  },
  {
    id: "t0263-006-065",
    category: "普現佛德",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "唯然世尊，垂加大恩，普現一切十方國土諸佛聖德。",
    anchorText: "垂加大恩，普現一切十方國土諸佛聖德",
    note: "大辩请佛普现十方诸佛圣德，令会众得见诸佛境界。",
  },
  {
    id: "t0263-006-066",
    category: "聞法啟受",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "爲諸衆生講説經法，音聲柔和靡不解達，百千菩薩啓受所聞。",
    anchorText: "爲諸衆生講説經法，音聲柔和",
    note: "十方诸佛为众生讲说经法，音声柔和，菩萨启受所闻。",
  },
  {
    id: "t0263-006-067",
    category: "瞻禮二佛",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "汝輩當徃詣忍世界見能仁佛如來、至真，并當瞻戴多寶世尊形像塔寺。",
    anchorText: "汝輩當徃詣忍世界見能仁佛",
    note: "十方诸佛劝诸菩萨往诣忍世界，见释迦如来并瞻戴多宝佛塔。",
  },
  {
    id: "t0263-006-068",
    category: "大道德相",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "各從十方諸佛刹土而來到此，顯示大道無極之德。",
    anchorText: "各從十方諸佛刹土而來到此",
    note: "十方诸佛来集，显示大道无极之德。",
  },
  {
    id: "t0263-006-069",
    category: "經法感現",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "善哉！善哉！釋迦文佛！説此經典，何其快乎！吾以欲聞此經法故，故自出現。",
    anchorText: "善哉！善哉！釋迦文佛",
    note: "多宝如来现身后亲口赞叹释迦说此经典，并明言为闻此经法而出现。",
  },
  {
    id: "t0263-006-070",
    category: "神力攝眾",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "佛知所念，現神足力，使四部衆自然超上處於虚空。",
    anchorText: "佛知所念，現神足力",
    note: "佛知四众愿处虚空的心念，以神足力令众自然升处虚空。",
  },
  {
    id: "t0263-006-071",
    category: "滅後持經",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "如來現在、若滅度後，當受此法持諷誦讀。",
    anchorText: "如來現在、若滅度後",
    note: "佛明令现在及灭后都应受持、讽诵、读此法。",
  },
  {
    id: "t0263-006-072",
    category: "奉敬經典",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "比丘當捨如來所供養供事之宜，奉順恭敬於此經典。",
    anchorText: "比丘當捨如來所供養",
    note: "佛将灭度时，特别劝比丘舍供事如来之宜，转而奉顺恭敬此经典。",
  },
  {
    id: "t0263-006-073",
    category: "聽法精進",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "比丘欲知，聽法故舉，何人省是，不興精進。",
    anchorText: "比丘欲知，聽法故舉",
    note: "偈颂说明多宝塔为听法而举现，见此因缘者应兴精进。",
  },
  {
    id: "t0263-006-074",
    category: "護法久住",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "皆欲將護，於正法故，何緣當今，經典久存？因由依附，諸佛之道",
    anchorText: "皆欲將護，於正法故",
    note: "十方诸佛为护正法而来，说明经典久存依附诸佛之道。",
  },
  {
    id: "t0263-006-075",
    category: "持經授決",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "吾滅度之後，其持此經典，速逮得受決，目見世導師。",
    anchorText: "吾滅度之後，其持此經典",
    note: "佛明说灭后持此经典者，速得授决，并得目见世导师。",
  },
  {
    id: "t0263-006-076",
    category: "聞法奉事",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "若聞此法，能受究竟，則爲奉事，歸命我身，并及多寶，如來之尊順，奉現在，十方諸佛。",
    anchorText: "若聞此法，能受究竟",
    note: "闻此法并究竟受持者，即为奉事释迦、多宝与现在十方诸佛。",
  },
  {
    id: "t0263-006-077",
    category: "受持供養",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "悉爲供養，具足無限，用遵修受，此經典故。",
    anchorText: "悉爲供養，具足無限",
    note: "遵修受此经典，即成对诸佛具足无限的供养。",
  },
  {
    id: "t0263-006-078",
    category: "末世奇特",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "佛滅度之後，末世能堪受頒，宣此經典，爾乃爲奇特。",
    anchorText: "佛滅度之後，末世能堪受頒",
    note: "佛以多重难事作比，指出灭后末世能受持宣此经才是真奇特。",
  },
  {
    id: "t0263-006-079",
    category: "書經奇特",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "我滅度之後，若歸如是像，來世書是經，爾乃爲奇特。",
    anchorText: "我滅度之後，若歸如是像",
    note: "佛赞来世归敬此像而书写此经者，是难得奇特之行。",
  },
  {
    id: "t0263-006-080",
    category: "讀經殊勝",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "此者不爲難，精進無奇特，不如於來世，須臾讀此經。",
    anchorText: "不如於來世，須臾讀此經",
    note: "偈颂以举地至梵天为比，反显来世须臾读此经更为殊胜。",
  },
  {
    id: "t0263-006-081",
    category: "一人說經",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "我滅度之後，若持此經典，爲一人説者，爾乃爲殊特。",
    anchorText: "我滅度之後，若持此經典",
    note: "佛赞灭后持此经典，即使只为一人说，也是殊特难得。",
  },
  {
    id: "t0263-006-082",
    category: "信喜咨講",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "持此經典，信喜而愛樂，數數咨講者，爾乃爲殊特。",
    anchorText: "持此經典，信喜而愛樂",
    note: "信喜爱乐、屡屡咨讲此经者，经文称为殊特。",
  },
  {
    id: "t0263-006-083",
    category: "持經功報",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "佛滅度之後，設持此經者，其人得功報，過是難限量。",
    anchorText: "佛滅度之後，設持此經者",
    note: "佛以为无数无著圣者立塔作比，赞灭后持此经者功报更过其上、难以限量。",
  },
  {
    id: "t0263-006-084",
    category: "經中之尊",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "計是經典者，一切經中尊，其奉持此典，則侍諸佛身。",
    anchorText: "計是經典者，一切經中尊",
    note: "佛明称此经典为一切经中之尊，奉持此典即如侍奉诸佛身。",
  },
  {
    id: "t0263-006-085",
    category: "須臾持經",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "須臾持此經，則爲奉敬佛，一切諸導師，是經難值遇。",
    anchorText: "須臾持此經",
    note: "片刻持此经即为奉敬诸佛导师，并说明此经难得值遇。",
  },
  {
    id: "t0263-006-086",
    category: "諸佛愛樂",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "一切十方佛，爲現所咨嗟，勇猛有威神，神通爲巳達。名德遠流布，諸佛所愛樂因，持此經故，逮得寂定地。",
    anchorText: "一切十方佛，爲現所咨嗟",
    note: "十方诸佛咨嗟持经者，称其名德远流布，并因持此经得寂定地。",
  },
  {
    id: "t0263-006-087",
    category: "世間眼目",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "導師滅度後，則爲天世人，顯示作眼目，宣布此經故。",
    anchorText: "導師滅度後，則爲天世人",
    note: "佛灭度后宣布此经者，为天与世人显示作眼目。",
  },
  {
    id: "t0263-006-088",
    category: "說經受禮",
    sectionTitle: QIBAO_TA_SECTION_TITLE,
    text: "於當來之世，須臾説此典，其一切衆生，稽首禮明者",
    anchorText: "於當來之世，須臾説此典",
    note: "未来世能须臾说此典者，经文说一切众生应稽首礼敬。",
  },
];
