source 'https://cdn.cocoapods.org/'

platform :osx, '10.15'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'ephemeral', 'Flutter-Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure \"flutter pub get\" is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Flutter-Generated.xcconfig, then run \"flutter pub get\""
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_macos_podfile_setup

def remove_invalid_flutter_sound_macos_pod(application_path)
  plugins_file = File.join(application_path, '..', '.flutter-plugins-dependencies')
  return unless File.exist?(plugins_file)

  require 'json'
  dependencies = JSON.parse(File.read(plugins_file))
  macos_plugins = dependencies.dig('plugins', 'macos')
  return unless macos_plugins.is_a?(Array)

  filtered_plugins = macos_plugins.reject { |plugin| plugin['name'] == 'flutter_sound' }
  return if filtered_plugins.length == macos_plugins.length

  dependencies['plugins']['macos'] = filtered_plugins
  File.write(plugins_file, JSON.generate(dependencies))
end

target 'Runner' do
  use_frameworks!

  application_path = File.dirname(File.realpath(__FILE__))
  remove_invalid_flutter_sound_macos_pod application_path
  flutter_install_all_macos_pods application_path
  
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_macos_build_settings(target)
    
    # 修复部署目标版本
    target.build_configurations.each do |config|
      if config.build_settings['MACOSX_DEPLOYMENT_TARGET'].to_f < 10.15
        config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.15'
      end
    end
  end
end
