#!/bin/bash
# 清除Cloudflare缓存的脚本

echo "🧹 清除Cloudflare缓存..."
echo ""
echo "请按照以下步骤操作："
echo ""
echo "1. 访问 Cloudflare Dashboard:"
echo "   https://dash.cloudflare.com"
echo ""
echo "2. 选择域名: ombhrum.com"
echo ""
echo "3. 点击左侧菜单: Caching > Configuration"
echo ""
echo "4. 找到 'Purge Cache' 部分"
echo ""
echo "5. 点击 'Purge Everything' 按钮"
echo ""
echo "6. 确认清除"
echo ""
echo "⏳ 等待1-2分钟让缓存清除生效"
echo ""
echo "7. 访问网站并硬刷新:"
echo "   https://flutter.ombhrum.com"
echo "   按 Cmd+Shift+R (Mac) 或 Ctrl+Shift+R (Windows)"
echo ""
echo "💡 提示: 也可以使用无痕模式测试"
