/// 全球国家服务器和名称映射
///
/// 此文件根据原生Web应用中的 `global-country-servers.js` 文件移植而来。
/// `GLOBAL_COUNTRY_SERVERS` 包含了每个国家代码对应的服务器URL列表。
/// `COUNTRY_NAMES` 提供了国家代码到中文名称的映射。

const Map<String, List<String>> GLOBAL_COUNTRY_SERVERS = {
  'AF': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'AX': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'AL': ['https://httpbin.org/post', 'https://reqres.in/api/posts'],
  'DZ': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'AS': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'AD': ['https://reqres.in/api/users', 'https://jsonplaceholder.typicode.com/posts'],
  'AO': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'AI': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'AQ': ['https://reqres.in/api/posts', 'https://reqres.in/api/users'],
  'AG': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'AR': ['https://httpbin.org/post', 'https://httpbin.org/post', 'https://reqres.in/api/users'],
  'AM': ['https://reqres.in/api/users', 'https://jsonplaceholder.typicode.com/posts'],
  'AW': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'AU': [
    'https://jsonplaceholder.typicode.com/posts',
    'https://reqres.in/api/users',
    'https://httpbin.org/post',
  ],
  'AT': ['https://reqres.in/api/posts', 'https://reqres.in/api/users'],
  'AZ': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'BS': ['https://httpbin.org/post', 'https://httpbin.org/post'],
  'BH': ['https://reqres.in/api/users', 'https://jsonplaceholder.typicode.com/posts'],
  'BD': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'BB': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'BY': ['https://reqres.in/api/posts', 'https://reqres.in/api/users'],
  'BE': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'BZ': ['https://httpbin.org/post', 'https://httpbin.org/post'],
  'BJ': ['https://reqres.in/api/users', 'https://jsonplaceholder.typicode.com/posts'],
  'BM': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'BT': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'BO': ['https://reqres.in/api/posts', 'https://reqres.in/api/users'],
  'BQ': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'BA': ['https://httpbin.org/post', 'https://httpbin.org/post'],
  'BW': ['https://reqres.in/api/users', 'https://jsonplaceholder.typicode.com/posts'],
  'BV': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'BR': [
    'https://jsonplaceholder.typicode.com/posts',
    'https://reqres.in/api/users',
    'https://httpbin.org/post',
  ],
  'IO': ['https://reqres.in/api/posts', 'https://reqres.in/api/users'],
  'BN': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'BG': ['https://httpbin.org/post', 'https://httpbin.org/post'],
  'BF': ['https://reqres.in/api/users', 'https://jsonplaceholder.typicode.com/posts'],
  'BI': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'CV': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'KH': ['https://reqres.in/api/posts', 'https://reqres.in/api/users'],
  'CM': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'CA': ['https://httpbin.org/post', 'https://httpbin.org/post', 'https://reqres.in/api/users'],
  'KY': ['https://reqres.in/api/users', 'https://jsonplaceholder.typicode.com/posts'],
  'CF': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'TD': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'CL': ['https://reqres.in/api/posts', 'https://reqres.in/api/users'],
  'CN': [
    'https://httpbin.org/post',
    'https://jsonplaceholder.typicode.com/posts',
    'https://httpbin.org/post',
  ],
  'CX': ['https://jsonplaceholder.typicode.com/posts', 'https://httpbin.org/post'],
  'CC': ['https://reqres.in/api/users', 'https://jsonplaceholder.typicode.com/posts'],
  'CO': ['https://httpbin.org/post', 'https://reqres.in/api/posts'],
  'KM': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'CD': ['https://httpbin.org/post', 'https://reqres.in/api/users'],
  'CG': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'CK': ['https://jsonplaceholder.typicode.com/posts', 'https://httpbin.org/post'],
  'CR': ['https://reqres.in/api/users', 'https://jsonplaceholder.typicode.com/posts'],
  'CI': ['https://httpbin.org/post', 'https://reqres.in/api/posts'],
  'HR': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'CU': ['https://httpbin.org/post', 'https://reqres.in/api/users'],
  'CW': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'CY': ['https://jsonplaceholder.typicode.com/posts', 'https://httpbin.org/post'],
  'CZ': ['https://reqres.in/api/users', 'https://jsonplaceholder.typicode.com/posts'],
  'DK': ['https://httpbin.org/post', 'https://reqres.in/api/posts', 'https://reqres.in/api/users'],
  'DJ': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'DM': ['https://httpbin.org/post', 'https://reqres.in/api/users'],
  'DO': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'EC': ['https://jsonplaceholder.typicode.com/posts', 'https://httpbin.org/post'],
  'EG': ['https://reqres.in/api/users', 'https://jsonplaceholder.typicode.com/posts'],
  'SV': ['https://httpbin.org/post', 'https://reqres.in/api/posts'],
  'GQ': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'ER': ['https://httpbin.org/post', 'https://reqres.in/api/users'],
  'EE': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'SZ': ['https://jsonplaceholder.typicode.com/posts', 'https://httpbin.org/post'],
  'ET': ['https://reqres.in/api/users', 'https://jsonplaceholder.typicode.com/posts'],
  'FK': ['https://httpbin.org/post', 'https://reqres.in/api/posts'],
  'FO': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'FJ': ['https://httpbin.org/post', 'https://reqres.in/api/users'],
  'FI': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'FR': [
    'https://jsonplaceholder.typicode.com/posts',
    'https://httpbin.org/post',
    'https://reqres.in/api/users',
  ],
  'GF': ['https://reqres.in/api/users', 'https://jsonplaceholder.typicode.com/posts'],
  'PF': ['https://httpbin.org/post', 'https://reqres.in/api/posts'],
  'TF': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'GA': ['https://httpbin.org/post', 'https://reqres.in/api/users'],
  'GM': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'GE': ['https://jsonplaceholder.typicode.com/posts', 'https://httpbin.org/post'],
  'DE': [
    'https://reqres.in/api/users',
    'https://jsonplaceholder.typicode.com/posts',
    'https://httpbin.org/post',
  ],
  'GH': ['https://httpbin.org/post', 'https://reqres.in/api/posts'],
  'GI': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'GR': ['https://httpbin.org/post', 'https://reqres.in/api/users'],
  'GL': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'GD': ['https://jsonplaceholder.typicode.com/posts', 'https://httpbin.org/post'],
  'GP': ['https://reqres.in/api/users', 'https://jsonplaceholder.typicode.com/posts'],
  'GU': ['https://httpbin.org/post', 'https://reqres.in/api/posts'],
  'GT': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'GG': ['https://httpbin.org/post', 'https://reqres.in/api/users'],
  'GN': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'GW': ['https://jsonplaceholder.typicode.com/posts', 'https://httpbin.org/post'],
  'GY': ['https://reqres.in/api/users', 'https://jsonplaceholder.typicode.com/posts'],
  'HT': ['https://httpbin.org/post', 'https://reqres.in/api/posts'],
  'HM': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'VA': ['https://httpbin.org/post', 'https://reqres.in/api/users'],
  'HN': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'HK': ['https://jsonplaceholder.typicode.com/posts', 'https://httpbin.org/post'],
  'HU': ['https://reqres.in/api/users', 'https://jsonplaceholder.typicode.com/posts'],
  'IS': ['https://httpbin.org/post', 'https://reqres.in/api/posts'],
  'IN': [
    'https://jsonplaceholder.typicode.com/posts',
    'https://reqres.in/api/users',
    'https://httpbin.org/post',
  ],
  'ID': ['https://httpbin.org/post', 'https://reqres.in/api/users'],
  'IR': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'IQ': ['https://jsonplaceholder.typicode.com/posts', 'https://httpbin.org/post'],
  'IE': ['https://reqres.in/api/users', 'https://jsonplaceholder.typicode.com/posts'],
  'IM': ['https://httpbin.org/post', 'https://reqres.in/api/posts'],
  'IL': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'IT': ['https://httpbin.org/post', 'https://reqres.in/api/users', 'https://httpbin.org/post'],
  'JM': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'JP': ['https://jsonplaceholder.typicode.com/posts', 'https://httpbin.org/post'],
  'JE': ['https://reqres.in/api/users', 'https://jsonplaceholder.typicode.com/posts'],
  'JO': ['https://httpbin.org/post', 'https://reqres.in/api/posts'],
  'KZ': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'KE': ['https://httpbin.org/post', 'https://reqres.in/api/users'],
  'KI': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'KP': ['https://jsonplaceholder.typicode.com/posts', 'https://httpbin.org/post'],
  'KR': [
    'https://reqres.in/api/users',
    'https://jsonplaceholder.typicode.com/posts',
    'https://httpbin.org/post',
  ],
  'KW': ['https://httpbin.org/post', 'https://reqres.in/api/posts'],
  'KG': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'LA': ['https://httpbin.org/post', 'https://reqres.in/api/users'],
  'LV': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'LB': ['https://jsonplaceholder.typicode.com/posts', 'https://httpbin.org/post'],
  'LS': ['https://reqres.in/api/users', 'https://jsonplaceholder.typicode.com/posts'],
  'LR': ['https://httpbin.org/post', 'https://reqres.in/api/posts'],
  'LY': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'LI': ['https://httpbin.org/post', 'https://reqres.in/api/users'],
  'LT': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'LU': ['https://jsonplaceholder.typicode.com/posts', 'https://httpbin.org/post'],
  'MO': ['https://reqres.in/api/users', 'https://jsonplaceholder.typicode.com/posts'],
  'MG': ['https://httpbin.org/post', 'https://reqres.in/api/posts'],
  'MW': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'MY': ['https://httpbin.org/post', 'https://reqres.in/api/users'],
  'MV': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'ML': ['https://jsonplaceholder.typicode.com/posts', 'https://httpbin.org/post'],
  'MT': ['https://reqres.in/api/users', 'https://jsonplaceholder.typicode.com/posts'],
  'MH': ['https://httpbin.org/post', 'https://reqres.in/api/posts'],
  'MQ': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'MR': ['https://httpbin.org/post', 'https://reqres.in/api/users'],
  'MU': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'YT': ['https://jsonplaceholder.typicode.com/posts', 'https://httpbin.org/post'],
  'MX': [
    'https://reqres.in/api/users',
    'https://jsonplaceholder.typicode.com/posts',
    'https://httpbin.org/post',
  ],
  'FM': ['https://httpbin.org/post', 'https://reqres.in/api/posts'],
  'MD': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'MC': ['https://httpbin.org/post', 'https://reqres.in/api/users'],
  'MN': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'ME': ['https://jsonplaceholder.typicode.com/posts', 'https://httpbin.org/post'],
  'MS': ['https://reqres.in/api/users', 'https://jsonplaceholder.typicode.com/posts'],
  'MA': ['https://httpbin.org/post', 'https://reqres.in/api/posts'],
  'MZ': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'MM': ['https://httpbin.org/post', 'https://reqres.in/api/users'],
  'NA': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'NR': ['https://jsonplaceholder.typicode.com/posts', 'https://httpbin.org/post'],
  'NP': ['https://reqres.in/api/users', 'https://jsonplaceholder.typicode.com/posts'],
  'NL': ['https://httpbin.org/post', 'https://reqres.in/api/posts', 'https://reqres.in/api/users'],
  'NC': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'NZ': ['https://httpbin.org/post', 'https://reqres.in/api/users'],
  'NI': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'NE': ['https://jsonplaceholder.typicode.com/posts', 'https://httpbin.org/post'],
  'NG': ['https://reqres.in/api/users', 'https://jsonplaceholder.typicode.com/posts'],
  'NU': ['https://httpbin.org/post', 'https://reqres.in/api/posts'],
  'NF': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'MK': ['https://httpbin.org/post', 'https://reqres.in/api/users'],
  'MP': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'NO': ['https://jsonplaceholder.typicode.com/posts', 'https://httpbin.org/post'],
  'OM': ['https://reqres.in/api/users', 'https://jsonplaceholder.typicode.com/posts'],
  'PK': ['https://httpbin.org/post', 'https://reqres.in/api/posts'],
  'PW': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'PS': ['https://httpbin.org/post', 'https://reqres.in/api/users'],
  'PA': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'PG': ['https://jsonplaceholder.typicode.com/posts', 'https://httpbin.org/post'],
  'PY': ['https://reqres.in/api/users', 'https://jsonplaceholder.typicode.com/posts'],
  'PE': ['https://httpbin.org/post', 'https://reqres.in/api/posts'],
  'PH': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'PN': ['https://httpbin.org/post', 'https://reqres.in/api/users'],
  'PL': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'PT': ['https://jsonplaceholder.typicode.com/posts', 'https://httpbin.org/post'],
  'PR': ['https://reqres.in/api/users', 'https://jsonplaceholder.typicode.com/posts'],
  'QA': ['https://httpbin.org/post', 'https://reqres.in/api/posts'],
  'RE': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'RO': ['https://httpbin.org/post', 'https://reqres.in/api/users'],
  'RU': [
    'https://httpbin.org/post',
    'https://jsonplaceholder.typicode.com/posts',
    'https://jsonplaceholder.typicode.com/posts',
  ],
  'RW': ['https://reqres.in/api/posts', 'https://httpbin.org/post'],
  'BL': ['https://reqres.in/api/users', 'https://jsonplaceholder.typicode.com/posts'],
  'SH': ['https://httpbin.org/post', 'https://httpbin.org/post'],
  'KN': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'LC': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'MF': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'PM': ['https://reqres.in/api/posts', 'https://httpbin.org/post'],
  'VC': ['https://reqres.in/api/users', 'https://jsonplaceholder.typicode.com/posts'],
  'WS': ['https://httpbin.org/post', 'https://httpbin.org/post'],
  'SM': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'ST': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'SA': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'SN': ['https://reqres.in/api/posts', 'https://httpbin.org/post'],
  'RS': ['https://reqres.in/api/users', 'https://jsonplaceholder.typicode.com/posts'],
  'SC': ['https://httpbin.org/post', 'https://httpbin.org/post'],
  'SL': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'SG': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'SX': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'SK': ['https://reqres.in/api/posts', 'https://httpbin.org/post'],
  'SI': ['https://reqres.in/api/users', 'https://jsonplaceholder.typicode.com/posts'],
  'SB': ['https://httpbin.org/post', 'https://httpbin.org/post'],
  'SO': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'ZA': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'GS': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'SS': ['https://reqres.in/api/posts', 'https://httpbin.org/post'],
  'ES': [
    'https://reqres.in/api/users',
    'https://jsonplaceholder.typicode.com/posts',
    'https://httpbin.org/post',
  ],
  'LK': ['https://httpbin.org/post', 'https://httpbin.org/post'],
  'SD': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'SR': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'SJ': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'SE': ['https://reqres.in/api/posts', 'https://httpbin.org/post'],
  'CH': ['https://reqres.in/api/users', 'https://jsonplaceholder.typicode.com/posts'],
  'SY': ['https://httpbin.org/post', 'https://httpbin.org/post'],
  'TW': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'TJ': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'TZ': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'TH': ['https://reqres.in/api/posts', 'https://httpbin.org/post'],
  'TL': ['https://reqres.in/api/users', 'https://jsonplaceholder.typicode.com/posts'],
  'TG': ['https://httpbin.org/post', 'https://httpbin.org/post'],
  'TK': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'TO': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'TT': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'TN': ['https://reqres.in/api/posts', 'https://httpbin.org/post'],
  'TR': ['https://reqres.in/api/users', 'https://jsonplaceholder.typicode.com/posts'],
  'TM': ['https://httpbin.org/post', 'https://httpbin.org/post'],
  'TC': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'TV': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'UG': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'UA': ['https://reqres.in/api/posts', 'https://httpbin.org/post'],
  'AE': ['https://reqres.in/api/users', 'https://jsonplaceholder.typicode.com/posts'],
  'GB': ['https://httpbin.org/post', 'https://httpbin.org/post', 'https://reqres.in/api/users'],
  'UM': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'US': [
    'https://jsonplaceholder.typicode.com/posts',
    'https://reqres.in/api/users',
    'https://httpbin.org/post',
  ],
  'UY': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'UZ': ['https://reqres.in/api/posts', 'https://httpbin.org/post'],
  'VU': ['https://reqres.in/api/users', 'https://jsonplaceholder.typicode.com/posts'],
  'VE': ['https://httpbin.org/post', 'https://httpbin.org/post'],
  'VN': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'VG': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'VI': ['https://httpbin.org/post', 'https://jsonplaceholder.typicode.com/posts'],
  'WF': ['https://reqres.in/api/posts', 'https://httpbin.org/post'],
  'EH': ['https://reqres.in/api/users', 'https://jsonplaceholder.typicode.com/posts'],
  'YE': ['https://httpbin.org/post', 'https://httpbin.org/post'],
  'ZM': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
  'ZW': ['https://jsonplaceholder.typicode.com/posts', 'https://reqres.in/api/users'],
};

const Map<String, String> COUNTRY_NAMES = {
  'AF': '阿富汗',
  'AX': '奥兰群岛',
  'AL': '阿尔巴尼亚',
  'DZ': '阿尔及利亚',
  'AS': '美属萨摩亚',
  'AD': '安道尔',
  'AO': '安哥拉',
  'AI': '安圭拉',
  'AQ': '南极洲',
  'AG': '安提瓜和巴布达',
  'AR': '阿根廷',
  'AM': '亚美尼亚',
  'AW': '阿鲁巴',
  'AU': '澳大利亚',
  'AT': '奥地利',
  'AZ': '阿塞拜疆',
  'BS': '巴哈马',
  'BH': '巴林',
  'BD': '孟加拉国',
  'BB': '巴巴多斯',
  'BY': '白俄罗斯',
  'BE': '比利时',
  'BZ': '伯利兹',
  'BJ': '贝宁',
  'BM': '百慕大',
  'BT': '不丹',
  'BO': '玻利维亚',
  'BQ': '博内尔、圣尤斯特歇斯和萨巴',
  'BA': '波斯尼亚和黑塞哥维那',
  'BW': '博茨瓦纳',
  'BV': '布维岛',
  'BR': '巴西',
  'IO': '英属印度洋领地',
  'BN': '文莱达鲁萨兰国',
  'BG': '保加利亚',
  'BF': '布基纳法索',
  'BI': '布隆迪',
  'CV': '佛得角',
  'KH': '柬埔寨',
  'CM': '喀麦隆',
  'CA': '加拿大',
  'KY': '开曼群岛',
  'CF': '中非共和国',
  'TD': '乍得',
  'CL': '智利',
  'CN': '中国',
  'CX': '圣诞岛',
  'CC': '科科斯（基林）群岛',
  'CO': '哥伦比亚',
  'KM': '科摩罗',
  'CD': '刚果民主共和国',
  'CG': '刚果',
  'CK': '库克群岛',
  'CR': '哥斯达黎加',
  'CI': '科特迪瓦',
  'HR': '克罗地亚',
  'CU': '古巴',
  'CW': '库拉索',
  'CY': '塞浦路斯',
  'CZ': '捷克共和国',
  'DK': '丹麦',
  'DJ': '吉布提',
  'DM': '多米尼克',
  'DO': '多米尼加共和国',
  'EC': '厄瓜多尔',
  'EG': '埃及',
  'SV': '萨尔瓦多',
  'GQ': '赤道几内亚',
  'ER': '厄立特里亚',
  'EE': '爱沙尼亚',
  'SZ': '斯威士兰',
  'ET': '埃塞俄比亚',
  'FK': '福克兰群岛（马尔维纳斯）',
  'FO': '法罗群岛',
  'FJ': '斐济',
  'FI': '芬兰',
  'FR': '法国',
  'GF': '法属圭亚那',
  'PF': '法属波利尼西亚',
  'TF': '法属南部领地',
  'GA': '加蓬',
  'GM': '冈比亚',
  'GE': '格鲁吉亚',
  'DE': '德国',
  'GH': '加纳',
  'GI': '直布罗陀',
  'GR': '希腊',
  'GL': '格陵兰',
  'GD': '格林纳达',
  'GP': '瓜德罗普',
  'GU': '关岛',
  'GT': '危地马拉',
  'GG': '根西',
  'GN': '几内亚',
  'GW': '几内亚比绍',
  'GY': '圭亚那',
  'HT': '海地',
  'HM': '赫德岛和麦克唐纳群岛',
  'VA': '梵蒂冈',
  'HN': '洪都拉斯',
  'HK': '香港',
  'HU': '匈牙利',
  'IS': '冰岛',
  'IN': '印度',
  'ID': '印度尼西亚',
  'IR': '伊朗',
  'IQ': '伊拉克',
  'IE': '爱尔兰',
  'IM': '马恩岛',
  'IL': '以色列',
  'IT': '意大利',
  'JM': '牙买加',
  'JP': '日本',
  'JE': '泽西',
  'JO': '约旦',
  'KZ': '哈萨克斯坦',
  'KE': '肯尼亚',
  'KI': '基里巴斯',
  'KP': '朝鲜',
  'KR': '韩国',
  'KW': '科威特',
  'KG': '吉尔吉斯斯坦',
  'LA': '老挝人民民主共和国',
  'LV': '拉脱维亚',
  'LB': '黎巴嫩',
  'LS': '莱索托',
  'LR': '利比里亚',
  'LY': '利比亚',
  'LI': '列支敦士登',
  'LT': '立陶宛',
  'LU': '卢森堡',
  'MO': '澳门',
  'MG': '马达加斯加',
  'MW': '马拉维',
  'MY': '马来西亚',
  'MV': '马尔代夫',
  'ML': '马里',
  'MT': '马耳他',
  'MH': '马绍尔群岛',
  'MQ': '马提尼克',
  'MR': '毛里塔尼亚',
  'MU': '毛里求斯',
  'YT': '马约特',
  'MX': '墨西哥',
  'FM': '密克罗尼西亚联邦',
  'MD': '摩尔多瓦',
  'MC': '摩纳哥',
  'MN': '蒙古',
  'ME': '黑山',
  'MS': '蒙特塞拉特',
  'MA': '摩洛哥',
  'MZ': '莫桑比克',
  'MM': '缅甸',
  'NA': '纳米比亚',
  'NR': '瑙鲁',
  'NP': '尼泊尔',
  'NL': '荷兰',
  'NC': '新喀里多尼亚',
  'NZ': '新西兰',
  'NI': '尼加拉瓜',
  'NE': '尼日尔',
  'NG': '尼日利亚',
  'NU': '纽埃',
  'NF': '诺福克岛',
  'MK': '北马其顿',
  'MP': '北马里亚纳群岛',
  'NO': '挪威',
  'OM': '阿曼',
  'PK': '巴基斯坦',
  'PW': '帕劳',
  'PS': '巴勒斯坦',
  'PA': '巴拿马',
  'PG': '巴布亚新几内亚',
  'PY': '巴拉圭',
  'PE': '秘鲁',
  'PH': '菲律宾',
  'PN': '皮特凯恩',
  'PL': '波兰',
  'PT': '葡萄牙',
  'PR': '波多黎各',
  'QA': '卡塔尔',
  'RE': '留尼汪',
  'RO': '罗马尼亚',
  'RU': '俄罗斯',
  'RW': '卢旺达',
  'BL': '圣巴泰勒米',
  'SH': '圣赫勒拿、阿森松和特里斯坦-达库尼亚',
  'KN': '圣基茨和尼维斯',
  'LC': '圣卢西亚',
  'MF': '法属圣马丁',
  'PM': '圣皮埃尔和密克隆',
  'VC': '圣文森特和格林纳丁斯',
  'WS': '萨摩亚',
  'SM': '圣马力诺',
  'ST': '圣多美和普林西比',
  'SA': '沙特阿拉伯',
  'SN': '塞内加尔',
  'RS': '塞尔维亚',
  'SC': '塞舌尔',
  'SL': '塞拉利昂',
  'SG': '新加坡',
  'SX': '荷属圣马丁',
  'SK': '斯洛伐克',
  'SI': '斯洛文尼亚',
  'SB': '所罗门群岛',
  'SO': '索马里',
  'ZA': '南非',
  'GS': '南乔治亚和南桑威奇群岛',
  'SS': '南苏丹',
  'ES': '西班牙',
  'LK': '斯里兰卡',
  'SD': '苏丹',
  'SR': '苏里南',
  'SJ': '斯瓦尔巴和扬马延',
  'SE': '瑞典',
  'CH': '瑞士',
  'SY': '叙利亚',
  'TW': '台湾',
  'TJ': '塔吉克斯坦',
  'TZ': '坦桑尼亚',
  'TH': '泰国',
  'TL': '东帝汶',
  'TG': '多哥',
  'TK': '托克劳',
  'TO': '汤加',
  'TT': '特立尼达和多巴哥',
  'TN': '突尼斯',
  'TR': '土耳其',
  'TM': '土库曼斯坦',
  'TC': '特克斯和凯科斯群岛',
  'TV': '图瓦卢',
  'UG': '乌干达',
  'UA': '乌克兰',
  'AE': '阿拉伯联合酋长国',
  'GB': '英国',
  'UM': '美国本土外小岛屿',
  'US': '美国',
  'UY': '乌拉圭',
  'UZ': '乌兹别克斯坦',
  'VU': '瓦努阿图',
  'VE': '委内瑞拉',
  'VN': '越南',
  'VG': '英属维尔京群岛',
  'VI': '美属维尔京群岛',
  'WF': '瓦利斯和富图纳',
  'EH': '西撒哈拉',
  'YE': '也门',
  'ZM': '赞比亚',
  'ZW': '津巴布韦',
};
