import 'package:flutter/material.dart';
import '../../models/user_activity_stats_model.dart';
import '../../services/user_activity_service.dart';

enum ActivityHeatmapMode { daily, weekly, cumulative }

class ActivityHeatmapWidget extends StatefulWidget {
  const ActivityHeatmapWidget({Key? key}) : super(key: key);

  @override
  State<ActivityHeatmapWidget> createState() => _ActivityHeatmapWidgetState();
}

class _ActivityHeatmapWidgetState extends State<ActivityHeatmapWidget> {
  ActivityHeatmapMode _currentMode = ActivityHeatmapMode.daily;
  UserActivitySummary? _summary;
  bool _isLoading = true;

  @override
  void initState() {
    super.initState();
    _loadData();
  }

  Future<void> _loadData() async {
    final summary = await UserActivityService().fetchActivityStats(context);
    if (mounted) {
      setState(() {
        _summary = summary;
        _isLoading = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            const Text(
              '活跃度热力图',
              style: TextStyle(
                color: Colors.white,
                fontSize: 16,
                fontWeight: FontWeight.w600,
              ),
            ),
            Row(
              children: [
                _buildModeToggle('每日', ActivityHeatmapMode.daily),
                const SizedBox(width: 12),
                _buildModeToggle('每周', ActivityHeatmapMode.weekly),
                const SizedBox(width: 12),
                _buildModeToggle('累计', ActivityHeatmapMode.cumulative),
              ],
            ),
          ],
        ),
        const SizedBox(height: 16),
        _isLoading
            ? const SizedBox(
                height: 110,
                child: Center(child: CircularProgressIndicator()),
              )
            : _buildHeatmapGrid(),
        const SizedBox(height: 8),
        _buildMonthsRow(),
      ],
    );
  }

  Widget _buildModeToggle(String label, ActivityHeatmapMode mode) {
    final isSelected = _currentMode == mode;
    return GestureDetector(
      onTap: () {
        setState(() {
          _currentMode = mode;
        });
      },
      child: Text(
        label,
        style: TextStyle(
          color: isSelected ? Colors.white : Colors.white54,
          fontSize: 13,
          fontWeight: isSelected ? FontWeight.w600 : FontWeight.normal,
        ),
      ),
    );
  }

  Widget _buildHeatmapGrid() {
    if (_summary == null) return const SizedBox(height: 110);

    // We need exactly 52 weeks * 7 days = 364 blocks to fit the grid.
    // The data generated by UserActivityService has 365 days, we take the last 364 to perfectly align 52 columns.
    
    List<UserActivityMetric> activeList;
    switch (_currentMode) {
      case ActivityHeatmapMode.daily:
        activeList = _summary!.dailyMetrics;
        break;
      case ActivityHeatmapMode.weekly:
        // Weekly metrics are grouped. Let's map them to 365 days by assigning the week's value to all days in that week
        activeList = _expandToDaily(_summary!.weeklyMetrics, _summary!.dailyMetrics);
        break;
      case ActivityHeatmapMode.cumulative:
        activeList = _summary!.cumulativeMetrics;
        break;
    }

    // Ensure we only use 364 days for exactly 52 weeks
    if (activeList.length > 364) {
      activeList = activeList.sublist(activeList.length - 364);
    }

    // Determine max values to calculate colors
    double maxTokens = 1.0;
    for (var m in activeList) {
      if (m.tokenCount > maxTokens) maxTokens = m.tokenCount.toDouble();
    }

    return SizedBox(
      height: 110,
      child: LayoutBuilder(
        builder: (context, constraints) {
          final boxWidth = (constraints.maxWidth - (51 * 4)) / 52;
          return Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: List.generate(52, (colIndex) {
              return Column(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: List.generate(7, (rowIndex) {
                  final dataIndex = colIndex * 7 + rowIndex;
                  if (dataIndex >= activeList.length) return SizedBox(width: boxWidth, height: 12);
                  
                  final metric = activeList[dataIndex];
                  
                  // Color calculation based on Token count density relative to max
                  Color cellColor = Colors.white.withOpacity(0.05);
                  if (metric.tokenCount > 0) {
                    final ratio = metric.tokenCount / maxTokens;
                    if (ratio > 0.75) {
                      cellColor = const Color(0xFF75A6E8); 
                    } else if (ratio > 0.4) {
                      cellColor = const Color(0xFF4A7BBE); 
                    } else if (ratio > 0.1) {
                      cellColor = const Color(0xFF2A5A9A); 
                    } else {
                      cellColor = const Color(0xFF1B3D6B); 
                    }
                  }

                  // Format strings for tooltip
                  final dateStr = "${metric.date.year}年${metric.date.month}月${metric.date.day}日";
                  
                  String titlePrefix = "";
                  if (_currentMode == ActivityHeatmapMode.daily) titlePrefix = "$dateStr 使用了";
                  else if (_currentMode == ActivityHeatmapMode.weekly) titlePrefix = "截至 $dateStr 当周使用了";
                  else if (_currentMode == ActivityHeatmapMode.cumulative) titlePrefix = "截至 $dateStr 累计使用了";

                  // Format Token (万/亿)
                  String tokenStr = "${metric.tokenCount}";
                  if (metric.tokenCount > 100000000) {
                    tokenStr = "${(metric.tokenCount / 100000000).toStringAsFixed(1)}亿";
                  } else if (metric.tokenCount > 10000) {
                    tokenStr = "${(metric.tokenCount / 10000).toStringAsFixed(1)}万";
                  }

                  return Tooltip(
                    padding: const EdgeInsets.all(12),
                    decoration: BoxDecoration(
                      color: const Color(0xFF1E1E1E),
                      borderRadius: BorderRadius.circular(8),
                      border: Border.all(color: Colors.white24),
                      boxShadow: [
                        BoxShadow(
                          color: Colors.black.withOpacity(0.5),
                          blurRadius: 10,
                          offset: const Offset(0, 4),
                        )
                      ],
                    ),
                    richMessage: TextSpan(
                      children: [
                        TextSpan(
                          text: "$titlePrefix $tokenStr 个 Token\n",
                          style: const TextStyle(color: Colors.white, fontSize: 13, fontWeight: FontWeight.bold),
                        ),
                        TextSpan(
                          text: "修行时间: ${metric.meditationMinutes} 分钟\n",
                          style: const TextStyle(color: Colors.white70, fontSize: 12),
                        ),
                        TextSpan(
                          text: "法布施: ${metric.dharmaDataMB.toStringAsFixed(1)} MB",
                          style: const TextStyle(color: Colors.white70, fontSize: 12),
                        ),
                      ],
                    ),
                    child: Container(
                      width: boxWidth,
                      height: 12,
                      decoration: BoxDecoration(
                        color: cellColor,
                        borderRadius: BorderRadius.circular(2),
                      ),
                    ),
                  );
                }),
              );
            }),
          );
        },
      ),
    );
  }

  // Expand weekly data to align perfectly with the daily grid visually
  List<UserActivityMetric> _expandToDaily(List<UserActivityMetric> weekly, List<UserActivityMetric> dailyRef) {
    List<UserActivityMetric> expanded = [];
    int weekIndex = 0;
    for (int i = 0; i < dailyRef.length; i++) {
      if (weekIndex < weekly.length - 1 && dailyRef[i].date.isAfter(weekly[weekIndex].date)) {
        weekIndex++;
      }
      final currentWeek = weekly[weekIndex];
      expanded.add(UserActivityMetric(
        date: dailyRef[i].date,
        tokenCount: currentWeek.tokenCount,
        meditationMinutes: currentWeek.meditationMinutes,
        dharmaDataMB: currentWeek.dharmaDataMB,
      ));
    }
    return expanded;
  }

  Widget _buildMonthsRow() {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceEvenly,
      children: const [
        Text('7月', style: TextStyle(color: Colors.white38, fontSize: 12)),
        Text('8月', style: TextStyle(color: Colors.white38, fontSize: 12)),
        Text('9月', style: TextStyle(color: Colors.white38, fontSize: 12)),
        Text('10月', style: TextStyle(color: Colors.white38, fontSize: 12)),
        Text('11月', style: TextStyle(color: Colors.white38, fontSize: 12)),
        Text('12月', style: TextStyle(color: Colors.white38, fontSize: 12)),
        Text('1月', style: TextStyle(color: Colors.white38, fontSize: 12)),
        Text('2月', style: TextStyle(color: Colors.white38, fontSize: 12)),
        Text('3月', style: TextStyle(color: Colors.white38, fontSize: 12)),
        Text('4月', style: TextStyle(color: Colors.white38, fontSize: 12)),
        Text('5月', style: TextStyle(color: Colors.white38, fontSize: 12)),
        Text('6月', style: TextStyle(color: Colors.white38, fontSize: 12)),
      ],
    );
  }
}
